- README.md
- docs/rules/prefer-empty.md
- lib/rules/prefer-empty.js
- tests/__snapshots__/index.test.js.snap
- tests/lib/rules/prefer-empty.js
see docs in this PR for details.  
new autofixable rule for `.toBeEmpty()` use cases.
fixes #7
> feat: new rule prefer-empty

- lib/createBannedAttributeRule.js
- lib/rules/prefer-empty.js
- lib/rules/prefer-focus.js
- lib/rules/prefer-to-have-attribute.js
This PR replaces usage of non standard fields start, end with range. (based on https://github.com/jest-community/eslint-plugin-jest/pull/221)
Properties start, end should not be used (they may be removed in feature)
currently those rules are crashing because of that if you decide to use (@typescript-eslint/parser)
see: https://eslint.org/docs/developer-guide/working-with-custom-parsers#all-nodes
fixes: #27
> fix: use range instead of start/end properties

- .travis.yml
- package.json
BREAKING CHANGE: Requires Node@^10.12.x || 12.x
BREAKING CHANGE: Requires ESLint@^7.x
Closes #45
> feat: Support ESLint 7.x

- docs/rules/prefer-empty.md
- src/__tests__/lib/rules/prefer-empty.js
- src/rules/prefer-empty.js
**What**:
- migrates `toBeEmpty` to `toBeEmptyDOMElement`
- fixes #55
**Why**:
`.toBeEmpty` was deprecated and `jest-dom` will cry.
**How**:
more or less find/replace `toBeEmpty` with `toBeEmptyDOMElement`
**Checklist**:
Anything else missing?
> feat: migrate toBeEmpty to toBeEmptyDOMElement

- docs/rules/prefer-empty.md
- src/__tests__/lib/rules/prefer-empty.js
- src/rules/prefer-empty.js
**What**: don't report (or fix) expect(el.innerHTML).toBe(foo)
**Why**: fixes https://github.com/testing-library/eslint-plugin-jest-dom/issues/61
**How**: added check for name if value is empty.
**Checklist**:
> fix: don't report expect(el.innerHTML).toBe(foo)

- docs/rules/prefer-checked.md
- package.json
- src/__tests__/__fixtures__/createBannedAttributeTestCases.js
- src/createBannedAttributeRule.js
**What**: fixes banned attribute checks with 2nd arg passed as non literal value.
**Why**: fixes https://github.com/testing-library/eslint-plugin-jest-dom/issues/58
**How**: add check for non literal 2nd arg, return null from fixer if present.
**Checklist**:
> fix(prefer-checked): don't auto-fix when 2nd argument is a non literal.

- src/__tests__/lib/rules/prefer-to-have-text-content.js
- src/rules/prefer-to-have-text-content.js
**What**: improve autofixing in prefer-to-have-text-content
**Why**: fixes #53 fixes #52 
**How**: more use of getText()
**Checklist**:
> fix(to-have-text-content): improved handling non literals and regex in autofix

- src/__tests__/lib/rules/prefer-to-have-text-content.js
- src/rules/prefer-to-have-text-content.js
**What**:
- Escape (RegExp) special characters in strings that are treated as regular expressions in the fixer for `toHaveTextContent`.
- Convert non-strings (eg: `100`) to a string before converting to a RegExp.
**Why**:
So the fixer works out-of-the-box without any additional manual fixes.
**How**:
- Using the snippet from MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Escaping
- Other relevant Stack Overflow answers:
- https://stackoverflow.com/a/6969486/2690790
- https://stackoverflow.com/a/3561711/2690790
**Checklist**:
> fix: escape special chars in regex for toHaveTextContent fixer

- package.json
- src/__tests__/lib/rules/prefer-empty.js
- src/rules/prefer-empty.js
**What**:
fixes bug that was reporting errors on non empty template strings in prefer-empty.
**Why**:
https://github.com/testing-library/eslint-plugin-jest-dom/issues/61#issuecomment-669211003
**How**:
added check for expressions.
**Checklist**:
> fix(prefer-empty): don't report on non empty template strings in to-be-empty

- src/__tests__/lib/rules/prefer-to-have-style.js
- src/rules/prefer-empty.js
- src/rules/prefer-to-have-style.js
**What**: ensure better handling of template literals
**Why**: so you don't get `undefined` in fixers
**How**: using `context.getSourceCode().getText(node)`
**Checklist**:
> fix: better handling of template literals

- package.json
**What**:
**Why**:
**How**:
**Checklist**:
> fix: pin kcd-scripts at 6.5

- smoke-test/repositories.json
- src/__tests__/lib/rules/prefer-in-document.js
- src/__tests__/lib/rules/prefer-to-have-style.js
- src/rules/prefer-in-document.js
- src/rules/prefer-to-have-style.js
**What**: fixing more use cases from smoke tests
**Why**: less bugs
fixes: #110
fixes: #114 
**How**:
**Checklist**:
> fix(rules): fixed bugs in prefer-to-have-style & prefer-in-document

- README.md
- src/__tests__/__fixtures__/createBannedAttributeTestCases.js
- src/__tests__/lib/rules/prefer-prefer-to-have-class.js
- src/assignment-ast.js
- src/createBannedAttributeRule.js
- src/rules/prefer-to-have-class.js
- src/rules/prefer-to-have-value.js
**What**:
**Why**:
**How**:
**Checklist**:
> fix(rules): improvements to rules that should only apply to dom nodes

- src/__tests__/lib/rules/prefer-to-have-value.js
- src/rules/prefer-to-have-value.js
**What**:
Only report errors for prefer-to-have-values if the query node is one of the accepted queries for toHaveValue i.e. a `ByRole("textdown")` or a `ByRole("dropdown")` query. Fixes #131 
**Why**:
Avoid reporting errors unless we know that the assertion is definitely erroneous.
**How**:
Check to see that the query and the query argument is valid before reporting an error.
**Checklist**:
> fix(rules): Only report prefer-to-have-value errors on accepted queries

- docs/rules/prefer-in-document.md
- src/__tests__/lib/rules/prefer-in-document.js
- src/rules/prefer-in-document.js
> Matches toBe(null) and toEqual(null) in addition to toBeNull() in prefer-document

- .github/dependabot.yml
Since this library is already using `dependabot-preview`, let's use the newest Dependabot version
> feat: add `dependabot.yml`

- src/__tests__/lib/rules/prefer-in-document.js
- src/rules/prefer-in-document.js
**What**:
It seems that `prefer-in-document` crashes in situations where it expected nodes to have an argument but they actually don't.
**Why**:
The rule assumes that if it's found the node its looking for, then the node has to have arguments and so makes property access keys in the first item in the args array without actually checking if its defined.
**How**:
I've added checks for the argument length before attempts to access said arguments.
**Checklist**:
> fix(prefer-in-document): check that a node has arguments before trying to access properties on them

- src/__tests__/__fixtures__/createBannedAttributeTestCases.js
- src/createBannedAttributeRule.js
**What**:
It seems that `createBannedAttributeRule` crashes in situations where it expected nodes to have an argument but they actually don't.
**Why**:
The function assumes that if it's found the node its looking for, then the node has to have arguments and so makes property access keys in the first item in the args array without actually checking if its defined.
**How**:
I added a length check on the arguments the matcher has.
**Checklist**:
Fixes #127
> fix(createBannedAttributeRule): check arguments length before accessing

- docs/rules/prefer-in-document.md
- src/__tests__/lib/rules/prefer-in-document.js
- src/rules/prefer-in-document.js
**What**: Autofix `toBeFalsy()` to `not.toBeInTheDocument()` and `toBeTruthy()` to `toBeInTheDocument()`.
**Why**: I noticed in our test code an occurrence of `expect(queryByText(XXX)).toBeFalsy()` which I think should be detected by this plugin.
**How**: I merely updated existing code.
**Checklist**:
> feat: [prefer-in-document] Detect and auto-fix `toBeFalsy()` and `toBeTruthy()`

- src/__tests__/lib/rules/prefer-to-have-attribute.js
- src/rules/prefer-to-have-attribute.js
**What**:
Bugfix to handle case where in circumstances that the matcher value has been intended as an empty string, the fixer incorrectly assumes the `.not` case.
**Why**:
The purpose of this fix is so that the code fixer can correctly match empty string attributes as differentiated from null or missing values.
**How**:
Do not treat an empty string as a null value.
**Checklist**:
Feel free to merge if approved.
> fix(prefer-to-have-attribute): Handle case where matcher value is empty string

- package.json
- src/__tests__/index.test.js
As requested by @G-Rath in https://github.com/testing-library/eslint-plugin-jest-dom/pull/200#issuecomment-979395884
Closes #228
> test: remove `jest-extended` usage

- .github/workflows/validate.yml
- package.json
As requested by @G-Rath in https://github.com/testing-library/eslint-plugin-jest-dom/pull/200#issuecomment-979395884
> chore(CI): support testing against multiple ESLint versions

- src/__tests__/lib/rules/prefer-empty.js
- src/__tests__/lib/rules/prefer-focus.js
- src/__tests__/lib/rules/prefer-in-document.js
- src/__tests__/lib/rules/prefer-prefer-to-have-class.js
- src/__tests__/lib/rules/prefer-to-have-attribute.js
- src/__tests__/lib/rules/prefer-to-have-style.js
- src/__tests__/lib/rules/prefer-to-have-text-content.js
- src/__tests__/lib/rules/prefer-to-have-value.js
- src/rules/prefer-in-document.js
**What**:
Fixes a crash caught by #229 in `prefer-in-document`
**Why**:
It assumes that `expect` calls have an argument, which semantically they should but syntactically is not correct.
**How**:
I've implemented a guard to ensure that the argument exists before trying to access any properties on it; have also added the test to the valid tests for every rule to ensure they can all handle the case.
**Checklist**:
> fix(prefer-in-document): check that argument exists before accessing

- src/__tests__/lib/rules/prefer-to-have-value.js
- src/assignment-ast.js
**What**:
Fixes a crash caught by #229 in `prefer-to-have-value`
**Why**:
It assumes that `property` will always be defined on the `queryNode` node if `callee.name` isn't, which is not always the case.
**How**:
I've implemented a guard to ensure that the property exists before trying to access it's `name`.
**Checklist**:
> fix(prefer-to-have-value): check that property exists before accessing

- .github/workflows/validate.yml
- package.json
- If we want to update our `@testing-library/dom` dependency to v8, we also need `Node@>=12`
https://github.com/testing-library/dom-testing-library/blob/1fc17bec5d28e5b58fcdd325d6d2caaff02dfb47/package.json#L23-L25
- If we want to update our `@typescript-eslint/parser` dependency to v5, we also need `Node@^12.22.0 || ^14.17.0 || >=16.0.0`
https://github.com/typescript-eslint/typescript-eslint/blob/b9407c560c8ab625fd546af73f71cce8178b9e05/package.json#L55-L57
- Node 10 is EOL, so it's a good practice to not support it anymore.
- ESLint 8.x requires `Node@^12.22.0 || ^14.17.0 || >=16.0.0` and imo it's a good practice to keep the Node version equal to that of the latest supported ESLint version
https://github.com/eslint/eslint/blob/fa4d4830a0e77f92154079ada17ffb893ce64232/package.json#L146-L1 …
> feat: drop Node 10 support

- src/__tests__/lib/rules/prefer-in-document.js
- src/rules/prefer-in-document.js
**What**:
**Why**:
**How**:
**Checklist**:
Fixes #249
> fix(prefer-in-document): don't crash on matchers that are not being called

- .github/workflows/validate.yml
- package.json
- src/rules/prefer-to-have-class.js
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉
---
Closes #190
Closes #252
Closes #253
> test: add ESLint 8.x tests

- src/__tests__/lib/rules/prefer-to-have-style.js
- src/rules/prefer-to-have-style.js
**What**:
Resolves #264 
Resolves #256 
**Why**:
Currently the rule errors due to incorrect fixes.
**How**:
I've adjusted the rule to handle number literals differently.
**Checklist**:
> fix(prefer-to-have-style): properly handle index access of `style` property

- src/__tests__/lib/rules/prefer-in-document.js
- src/rules/prefer-in-document.js
**What**:
1. For toHaveLength:
- Calling toHaveLength without any arguments causing .value on undefined object fixed. 
- if no argument provided, toHaveLength(), it is also considered as toHaveLengthZero together with toHaveLength(0).
2. matcherArgument removal logic in eslint fixer is updated to remove the commas also, if there were multiple args in the matcher.
**Why**:
1. toHaveLength method on expect is causing eslint to crash since no argument logic isn't handled properly in the prefer-in-document rule. If eslint is always watching and linting live, this issue is quite annoying.
Eslint plugin crush stack trace in VSCode:
Even after handling calling toHaveLength without any arguments, it won't work since toHaveLength expected argument is …
> fix(prefer-in-document): handle `toHaveLength` without any arguments and with trailing commas

- README.md
Related to #298 
To make the style of badges consistent.
**Checklist**:
> docs: use flat-square style for badges

- src/__tests__/lib/rules/prefer-to-have-style.js
- src/rules/prefer-to-have-style.js
**What**:
Changes `prefer-to-have-style` to not give an autofix if a variable is being used to access `style`.
**Why**:
Because it generates an invalid autofixer.
Note that we could probably do at least a suggestion (or two), but at this point I'm not too sure of the semantics and currently this is creating invalid code - if someone wants to do a followup PR that improves this rule, I'd be happy to review it.
**How**:
By not setting `fix` if the node is an `Identifier`.
**Checklist**:
Resolves #265
Resolves #286
(note I've purposely not formatted my code to test a theory)
> fix(prefer-to-have-style): do not offer invalid autofix for computed accessors

- README.md
- docs/rules/prefer-in-document.md
- src/__tests__/lib/rules/prefer-in-document.js
- src/rules/prefer-in-document.js
**What**:
Closes https://github.com/testing-library/eslint-plugin-jest-dom/issues/171
Closes #273
**Why**:
It's valid to use .toHaveLength(1) with *AllBy* queries to check for "exactly one match".
See conclusion of discussions at https://github.com/testing-library/eslint-plugin-jest-dom/issues/171#issuecomment-895074086
**How**:
Implement the truth table as described in the link above.
**Checklist**:
I basically just re-pushed #273 and made a few changes to the test suite.
> fix(prefer-in-document): false positive on .toHaveLength(1) matcher with *AllBy* query

- .github/workflows/validate.yml
**What**:
This reverts commit 575a831a77180a3cbe93aca27e0cf4b714530675.
**Why**:
The v4 action [seems](https://github.com/google/osv-scanner/pull/871) to be [broken](https://github.com/jest-community/eslint-plugin-jest/pull/1494); it might be a case of just setting up a token but I can't do that and also it seems like that might [not always solve the problem](https://github.com/codecov/codecov-action/issues/1248#issuecomment-1970946946).
Since this is a required status check that cannot be overridden (at least by me), it's blocking PRs.
**How**:
By reverting #325
**Checklist**:
> ci: downgrade `codecov/codecov-action`

- README.md
- docs/rules/prefer-in-document.md
For some reason these changes are wanted by CI but locally it wants the inverse
> docs: update eslint suggestions links

- .eslint-doc-generatorrc.js
- README.md
- package.json
- src/__tests__/index.test.js
- src/index.js
This adds support for ESLint v9's upcoming `eslint.config.js` while retaining backwards compatibility with `.eslintrc` - I've marked this as a breaking change since I had to change around the exports due to needing to reference the plugin in the flat configs and in turn decided to axe the config building functions as there was no need to export them.
**Checklist**:
> feat: add should-be-fine support for flat configs

- .github/workflows/validate.yml
This updates our matrix of Node versions to target the latest LTS versions of Node we support, optimizing CI to balance between giving us confidence in our support while still being easy to maintain; I'm comfortable not testing against exact versions since most people will be using the latest version within the particular major and really any issue would be the result of a bug in Node.
> ci: update matrix of node versions to test against

- .github/workflows/validate.yml
This reduces the amount of jobs that get run without a lot of risk since users are generally going to be using the latest minor.patch version of a particular major, and any issues are going to be the result of bugs in that major for which any fix will require a new version anyway.
> ci: only test against latest versions of ESLint majors

- .github/workflows/validate.yml
While it isn't erroring, it's not officially supported and excluding it removes a couple more CI jobs - I've also changed the order so that the thing with the requirement is listed as the first key in each item, which makes it a bit more logic and that way we can be consistent.
> ci: don't run `@testing-library/dom` v10 against Node 12.x

- .github/workflows/validate.yml
- package.json
- src/__tests__/lib/rules/prefer-empty.js
- src/__tests__/lib/rules/prefer-focus.js
- src/__tests__/lib/rules/prefer-in-document.js
- src/__tests__/lib/rules/prefer-prefer-to-have-class.js
- src/__tests__/lib/rules/prefer-to-have-attribute.js
- src/__tests__/lib/rules/prefer-to-have-style.js
- src/__tests__/lib/rules/prefer-to-have-text-content.js
- src/__tests__/lib/rules/prefer-to-have-value.js
- src/__tests__/rule-tester.js
- src/assignment-ast.js
- src/context.js
- src/rules/prefer-empty.js
- src/rules/prefer-in-document.js
- src/rules/prefer-to-have-attribute.js
- src/rules/prefer-to-have-class.js
- src/rules/prefer-to-have-style.js
- src/rules/prefer-to-have-text-content.js
- src/rules/prefer-to-have-value.js
**What**:
Adds support for ESLint v9, based on how I did it in `eslint-plugin-jest`
**Why**:
Because ESLint v9 is the future
**How**:
Magic
**Checklist**:
> feat: support ESLint v9
