testing-library/eslint-plugin-jest-dom

package.json
src/__tests__/__fixtures__/createBannedAttributeTestCases.js
src/createBannedAttributeRule.js

**What**:
Fixes https://github.com/testing-library/eslint-plugin-jest-dom/issues/49
**Why**:
so it doesn't auto-fix incorrectly.
**How**:
add check for `'true'`
**Checklist**:

fix: fixed bug w/ toHaveAttribute("aria-check", "true")

---

src/__tests__/lib/rules/prefer-to-have-attribute.js
src/rules/prefer-to-have-attribute.js

**What**: Fixes bug in prefer-to-have-attribute autofixer. 
**Why**: fixes https://github.com/testing-library/eslint-plugin-jest-dom/issues/52
**How**: use getText() instead of .raw
**Checklist**:

fix(to-have-attribute): fixed bug in prefer-to-have-attribute autofix

---

.travis.yml
package.json

**What**: Run tests in 6.8 & 7
**Why**: to ensure compatibility with both
**How**: in travis
**Checklist**:

chore: support eslint 6.8 and 7

---

src/__tests__/lib/rules/prefer-to-have-style.js
src/rules/prefer-to-have-style.js

**What**: Fixes issue with toHaveAttribute check.
**Why**: so unrelated code doesn't trigger error
**How**: fixed bug in selector for toHaveAttribute
**Checklist**:

fix: fixed bug in toHaveAttribute('style') check

---

docs/rules/prefer-focus.md
src/__tests__/lib/rules/prefer-focus.js

**What**:
Just fixing correct examples for `prefer-focus`
**Checklist**:

docs(prefer-focus): fix correct examples for prefer focus

---

src/__tests__/lib/rules/prefer-in-document.js
src/__tests__/lib/rules/prefer-prefer-to-have-class.js
src/rules/prefer-in-document.js
src/rules/prefer-to-have-class.js

**What**:
**Why**:
**How**:
**Checklist**:

fix(rules): added more use cases for to have class and in docucment

---

.github/workflows/eslint-plugin-jest-dom.yml
docs/rules/prefer-in-document.md
src/__tests__/lib/rules/prefer-in-document.js
src/rules/prefer-in-document.js

**What**:
**Why**:
**How**:
**Checklist**:

fix(rules): added more use cases for prefer-in-document

---

.github/workflows/eslint-plugin-jest-dom.yml

https://nodejs.medium.com/node-js-16-available-now-7f5099a97e70

chore: add tests for Node 16

---

.github/workflows/smoke-test.yml

**What**:
CI is failing.
**Why**:
Current CI is failing due to incompatible dependency:
```
error jest-regex-util@27.0.6: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "12.11.1"
```
**How**:
Bumps node version used by smoke-tests on CI to LTS.
**Checklist**:

test: fix CI node version

---

.github/workflows/eslint-plugin-jest-dom.yml
README.md
build/generate-readme-table.js
docs/rules/prefer-empty.md
other/MAINTAINING.md
smoke-test/repositories.json

as Git announced that main  should be your primary branch, I'm renaming all master references to main
**What**:
**Why**:
**How**:
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs)

chore: rename 'master' branch to 'main'

---

README.md

**What**: Fix the link to ESLint in the README file.
**Why**: The link not being displayed correctly.
**How**: Re-format the markdown.
**Checklist**:

docs: fix eslint link

---

.github/workflows/validate.yml

**What**:
Closes https://github.com/testing-library/eslint-plugin-jest-dom/issues/194
**Why**:
Release workflow no longer built files after https://github.com/testing-library/eslint-plugin-jest-dom/commit/48b7e2b44e1310991de677dc1981fc748d46c4ee. The commit was pushed without a PR for some reason. Unclear why since PRs are a vital tool to ensure changes are peer reviewed.
**How**:
Restore steps from https://github.com/testing-library/eslint-plugin-jest-dom/blob/eac998edba29debec7dda1257e3fbe3dbdf10fef/.github/workflows/eslint-plugin-jest-dom.yml that were not ported to https://github.com/testing-library/eslint-plugin-jest-dom/blob/48b7e2b44e1310991de677dc1981fc748d46c4ee/.github/workflows/validate.yml
**Checklist**:
- ~[ ]~ Documentation
- ~[ ]~ Tests

fix: Publish built source

---

package.json

As requested by @G-Rath in https://github.com/testing-library/eslint-plugin-jest-dom/pull/200#issuecomment-979395884

chore: update dependencies to latest minor version

---

docs/rules/prefer-required.md

**What**:
This will update the title of docs for `prefer-required` as it was mistakenly called `prefer-enabled-required`.
**Why**:
So the documentation has the correct name of the rule.
**How**:
See code changes.
**Checklist**:

chore: fix title of prefer-required in docs

---

.github/workflows/validate.yml

**What**:
Updates CI so that we don't `fail-fast`.
**Why**:
Because we're an open-source library so we don't get charged for CI time, so we might as well be running all of our checks in the matrix in case there are more failures.
**How**:
Modifying the workflow file.
**Checklist**:

ci: dont fail fast

---

.github/workflows/validate.yml
package.json

**What**:
Makes `@testing-library/dom` a required peer dependency.
**Why**:
This ensures that the same version of `@testing-library/dom` that is being used on projects is used as part of linting, along with allowing us to support more versions, and just overall reduce downstream pain.
Also see #238 for prior discussion
**How**:
By making `@testing-library/dom` a peer dependency.
**Checklist**:
Resolves #294
Resolves #301

feat: make `@testing-library/dom` a peer dependency

---

package.json

This makes running tests locally possible again

chore: add `@testing-library/dom` to `devDependencies`

---

package.json

**What**:
For some reason I didn't think to sort these, and now `npm` will do so on occasion when you do stuff - so sorting them now means less noise for folks.
**Why**:
**How**:
**Checklist**:

chore: sort peer dependencies

---

src/__tests__/__fixtures__/createBannedAttributeTestCases.js

**What**:
Noticed while doing #255 - these being arrays is not a meaningful thing and the fact that they work is luck.
**Why**:
**How**:
**Checklist**:

test: remove unneeded arrays

---

src/__tests__/lib/rules/prefer-to-have-style.js
src/rules/prefer-to-have-style.js

fix(prefer-to-have-style): handle `toHaveProperty` with variable property name

---

.github/workflows/validate.yml

Reverts testing-library/eslint-plugin-jest-dom#350
Also see #345

revert: downgrade `codecov/codecov-action` (again)

---

.github/workflows/validate.yml
package.json

feat: allow `testing-library/dom` v10

---

.github/workflows/validate.yml

ci: update matrix node version conditions

---

index.d.ts
package.json

**What**:
This adds a TypeScript declaration file
**Why**:
This makes TypeScript happy when using `eslint.config.js`
**How**:
I manually crafted the types based on the ones we're using in `eslint-plugin-jest`, as I didn't think it was worth automating at this point
**Checklist**:

feat: add TypeScript types
